### ISSUE TITLE
unexpected keyword argument 'serial_number'

### ISSUE THREAD

**Issue by louiehummv** [ablyler/home-assistant-bradford-white-connect#15]
Installed v.0.2.5 on Home Assistant v.2023.9.3 via HACS v.1.34.0. After starting up HA, got the following error for this component:
```
Log details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entriesSource: custom_components/bradford_white_connect/__init__.py:47Integration: Bradford White Connect (documentation, issues)First occurred: 6:44:44 PM (1 occurrences)Last logged: 6:44:44 PM
Error setting up entry xxxxxxxx@xxx.xxx for bradford_white_connect
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/bradford_white_connect/__init__.py", line 47, in async_setup_entry
    device_registry.async_get_or_create(
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
```
Went to that \_\_init\_\_.py file & commented out the line (a couple after line 47) that assigns the "serial_number". Then restarted HA and the component worked without errors.

Not sure how important that line is, but I don't mind missing my water heater's serial number. If there's a better fix, feel free to do so.

**Comment by ablyler** [comment]
Thanks, it seems like we should update the code to allow for these type of fields to be missing.

**Comment by ablyler** [comment]
This should be fixed in the latest release.

**Comment by louiehummv** [comment]
Updated to v.0.2.7 and the issue persists. Had to comment out the lines that assign the "serial_number".
